#!/bin/bash


HELPER(){
	if [[ "$1" = "--help" || "$1" = "-h" || "$#" = "0" ]]
	then
		echo -e "\njust tell me your project name :D\n\nLIKE THIS: snakep test\n"
		exit 0
	else
		echo -e "The $1 Exist!:\n\n`ls $1`"
		exit 1
	fi
}

LICENSES_CREATOR(){
	licenses=()

	count=1
	echo "0 - Nothing"
	for  license in `ls ~/.licenses`
	do
		licenses+=("$license")
		echo "$count - $license" | tr "_" " "
		let count+=1
	done
	echo "$((count+1)) - Empty License"



	try_again=0
	while [ $try_again -lt 2 ] 
	do
		read -p "Enter Your Number Of Choice: " choice

		if ! [[ $choice =~ "[0-9]+" ]];
		then
			if [[ $choice -lt $count && $choice -gt 0 ]]
			then
				cp ~/.licenses/${licenses[$choice-1]} ./LICENSE
				break

			elif [ $choice="((choice+1))" ]
			then
				touch LICENSE
				break

			elif [ $choice="0" ]
			then
				break

			else
				echo "$choice: Out Of Range!"
			fi
		fi

		if ! [[ $choice =~ "[a-zA-Z]+" ]];
		then
			echo "just number!"
		fi

		((try_again=try_again+1))
	done
}

FOLDER_CREATOR(){
	if [[ "$1" = "" || -d "$1" || "$1" = "--help" || "$1" = "-h" ]]
	then
		HELPER $1
	fi
	SAMPLE_PROJECT=~/.snakep
	SOURCE_COMMONDS=~/.snakep_commonds
	if mkdir $1;
	then
		# install all files or folders
		cp -r $SAMPLE_PROJECT/* $1
		# install all hiden files or folders
		cp $SAMPLE_PROJECT/.[a-zA-Z0-9]* $1 && cp -r $SAMPLE_PROJECT/.[a-zA-Z0-9]* $1
		cd $1
		LICENSES_CREATOR $1
		exec $SOURCE_COMMONDS
	else
		return 1
	fi
}

case "${1}" in
	"-h" | "--h" | "" ) HELPER $1 ;;
	*				  ) FOLDER_CREATOR $1 ;;
esac
