#!/bin/bash


HELPER(){
	if [[ "$1" = "--help" || "$1" = "-h" || "$#" = "0" ]]
	then
		echo -e "\njust tell me your project name :D\n\nLIKE THIS: snakep test\n"	
	else
		echo -e "The $1 Exist!:\n\n`ls $1`"
	fi
}


FOLDER_CREATOR(){
	if [[ "$1" = "" || -d "$1" || "$1" = "--help" || "$1" = "-h" ]]
	then
		HELPER $1
		return 1
	fi
	SAMPLE_PROJECT=~/.snakep
	SOURCE_COMMONDS=~/.snakep_commonds
	if mkdir $1;
	then
		# install all files or folders
		cp -r $SAMPLE_PROJECT/* $1
		# install all hiden files or folders
		cp $SAMPLE_PROJECT/.[a-zA-Z0-9]* $1 && cp -r $SAMPLE_PROJECT/.[a-zA-Z0-9]* $1
		cd $1
		exec $SOURCE_COMMONDS
	else
		return 1
	fi
}

case "${1}" in
	"-h" | "--h" | "" ) HELPER $1 ;;
	*				  ) FOLDER_CREATOR $1 ;;
esac
